import Footer from '@/components/layout/footer';
import Header from '@/components/layout/header';
import Main from '@/components/layout/main';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es-ES">
      <body className="grid grid-cols-12 w-100vw max-w-screen-[1920px] overflow-x-hidden">
        <Header />
        <Main />
        <Footer />
      </body>
    </html>
  );
}
